---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(caret)
library(randomForest)
library(xgboost)
library(GGally)
library(leaflet)
library(cluster)
library(factoextra)
library(glmnet)

library(PerformanceAnalytics)
```

```{r}
# Cargar los datasets
train <- read.csv("../train.csv")
test <- read.csv("../test.csv")
```

```{r}
# Ver las primeras filas del conjunto de entrenamiento
head(train)

# Resumen de los datos
summary(train)

# Distribución de la variable objetivo
ggplot(train, aes(x = median_house_value)) +
  geom_histogram(binwidth = 50000, fill = "blue", color = "black") +
  theme_minimal() +
  labs(title = "Distribución de median_house_value")

# Correlación entre las variables numéricas
num_vars <- train %>% select(-id, -ocean_proximity)
ggcorr(num_vars, label = TRUE)

# Relación entre median_income y median_house_value
ggplot(train, aes(x = median_income, y = median_house_value)) +
  geom_point(alpha = 0.3) +
  theme_minimal() +
  labs(title = "Relación entre median_income y median_house_value")

ggplot(train, aes(x = longitude, y = latitude, color = median_house_value)) +
  geom_point() +
  scale_color_gradient(low = "blue", high = "red") +
  labs(title = "Mapa de precios de casas por coordenadas",
       x = "Longitud",
       y = "Latitud",
       color = "Precio de la Casa")

ggplot(train, aes(x = longitude, y = latitude, color = ocean_proximity)) +
  geom_point()  +
  labs(title = "Mapa de precios de casas por coordenadas",
       x = "Longitud",
       y = "Latitud",
       color = "Cercania")

m <- leaflet(train) %>%
  addTiles() %>%
  addCircleMarkers(~longitude, ~latitude, radius = ~median_house_value/100000, 
                   color = ~ifelse(median_house_value > median(train$median_house_value), 'red', 'blue'), 
                   popup = ~paste("median_house_value:", median_house_value))

m
```

```{r}
continuas1 = c("longitude", "latitude", "housing_median_age", "total_rooms", "total_bedrooms", "population", "households", "median_income")

create_boxplot <- function(column_name) {
  ggplot(train, aes_string(x = "1", y = column_name)) +  # Usamos aes_string para la evaluación no estándar
    geom_boxplot() +
    labs(title = paste("Boxplot of", column_name), x = "", y = column_name) +
    theme_minimal()
}

plots <- lapply(continuas1, create_boxplot)

for (plot in plots) {
  show(plot)
}

```


```{r}
# Imputar valores nulos en total_bedrooms
train$total_bedrooms[is.na(train$total_bedrooms)] <- median(train$total_bedrooms, na.rm = TRUE)
test$total_bedrooms[is.na(test$total_bedrooms)] <- median(test$total_bedrooms, na.rm = TRUE)

# Codificar variables categóricas
train$ocean_proximity_num <- as.numeric(as.factor(train$ocean_proximity))
test$ocean_proximity_num <- as.numeric(as.factor(test$ocean_proximity))

# Escalar características numéricas
num_features <- names(train)[sapply(train, is.numeric) & names(train) != "median_house_value"]
preProcValues <- preProcess(train[, num_features], method = c("center", "scale"))
train[, num_features] <- predict(preProcValues, train[, num_features])

num_features <- names(test)[sapply(test, is.numeric) & names(test) != "id"]
preProcValues <- preProcess(test[, num_features], method = c("center", "scale"))
test[, num_features] <- predict(preProcValues, test[, num_features])
```

```{r}
train
```


```{r}
calcular_silueta_promedio <- function(data, k) {
  set.seed(42)
  kmeans_result <- kmeans(data, centers = k)
  silueta <- silhouette(kmeans_result$cluster, dist(data))
  mean(silueta[, 3])  # Promedio del coeficiente de silueta
}


# Calcular la silueta promedio para k = 2 a 10
k_values <- 2:15

fviz_nbclust(train[, c("longitude", "latitude", "median_house_value")], kmeans, method = "wss")

silueta_promedio <- sapply(k_values, function(k) calcular_silueta_promedio(train[, c("longitude", "latitude", "median_house_value")], k))


# Visualizar los resultados
plot(k_values, silueta_promedio, type = "b", pch = 19,
     xlab = "Número de Clusters (k)", ylab = "Coeficiente de Silueta Promedio",
     main = "Coeficiente de Silueta Promedio para Diferentes k")




```

```{r}
k_optimo <- k_values[which.max(silueta_promedio)]
print(paste("El número óptimo de clusters es:", k_optimo))
```


```{r}

# Establece el número de clusters
num_clusters <- 5

# Aplica el clustering K-Means
set.seed(42) # Para reproducibilidad
clusters <- kmeans(train[, c("longitude", "latitude", "median_house_value")], centers = num_clusters)

# Añade los clusters al dataframe
train$position_cluster <- as.factor(clusters$cluster)

# Visualiza los clusters
ggplot(train, aes(x = longitude, y = latitude, color = position_cluster)) +
  geom_point() +
  labs(title = "Clustering de casas por coordenadas",
       x = "Longitud",
       y = "Latitud",
       color = "Cluster")
```

```{r}
outliers = c("total_rooms", "total_bedrooms", "population", "households", "median_income")


preProcValues_min_max <- preProcess(train[, outliers], method = c("range"))
train_t3_normalized <- predict(preProcValues_min_max, train)

preProcValues_standard <- preProcess(train[, outliers], method = c("center", "scale"))
train_t3_standardized <- predict(preProcValues_standard, train)
```

```{r}
continuas1 = c("longitude", "latitude", "housing_median_age", "total_rooms", "total_bedrooms", "population", "households", "median_income")

create_boxplot <- function(column_name) {
  ggplot(train, aes_string(x = "1", y = column_name)) +  # Usamos aes_string para la evaluación no estándar
    geom_boxplot() +
    labs(title = paste("Boxplot of", column_name), x = "", y = column_name) +
    theme_minimal()
}

plots <- lapply(continuas1, create_boxplot)

for (plot in plots) {
  show(plot)
}




```

```{r}

for (column_name  in  continuas1) {
  
  vector_numerico = unlist(train[column_name])
  
  Q1 <- quantile(vector_numerico, 0.25)  # Primer cuartil (Q1)
  Q3 <- quantile(vector_numerico, 0.75)  # Tercer cuartil (Q3)
  IQR <- Q3 - Q1  # Rango intercuartílico
  
  # Definir los límites inferior y superior para identificar outliers
  limite_inferior <- Q1 - 1.5 * IQR
  limite_superior <- Q3 + 1.5 * IQR
  
  # Identificar los outliers
  outliers <- vector_numerico[vector_numerico < limite_inferior | vector_numerico > limite_superior]
  
  # Contar los outliers
  conteo_outliers <- length(outliers)
  
  # Resultados
  print(column_name)
  print(paste("Número de outliers identificados usando IQR:", conteo_outliers))
  print(paste("Prosnetaje de outliers identificados usando IQR:", conteo_outliers/nrow(train)))
}

chart.Correlation(train[continuas1], histogram=TRUE)

```


```{r}

set.seed(123)
control <- rfeControl(functions = rfFuncs, method = "cv", number = 5)
rfe_results <- rfe(train[, num_features], train$median_house_value, sizes = 5, rfeControl = control)

print(rfe_results)

selected_features <- predictors(rfe_results)
print(selected_features)


```
```{r}
selected_features = c(c("position_cluster"), selected_features)

```

```{r}
selected_features

```

```{r}

train_control <- trainControl(method = "cv", number = 5)

train_selected <- train[, c(selected_features, "median_house_value")]

rf_model <- train(median_house_value ~ ., data = train_selected, method = "rf", trControl = train_control)
print(rf_model)


xgb_grid <- expand.grid(
  nrounds = 50,
  max_depth = 6,
  eta = 0.3,
  gamma = 0,
  colsample_bytree = 1,
  min_child_weight = 1,
  subsample = 1
)

xgb_model <- train(median_house_value ~ ., data = train_selected, method = "xgbTree", trControl = train_control, tuneGrid = xgb_grid)
print(xgb_model)

results <- resamples(list(rf = rf_model, xgb = xgb_model))
summary(results)
```

```{r}
lista <- data.frame(ID = test$id,
                    median_house_value = predict(knn_predictions, test) )
write.table(lista, "respuesta.csv", sep = ",", row.names = FALSE)
```




